######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 10 16:46:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/anarsoul/work/v4l2ucp-qt4/. .

# Input
HEADERS += mainWindow.h v4l2controls.h
SOURCES += mainWindow.cpp v4l2controls.cpp v4l2ucp.cpp
